### ISSUE TITLE
Import error, can't find file: ./runConcent

### ISSUE THREAD

**Issue by p-null** [concentjs/react-router-concent#2]
The example given in the README may need an update.

It gives error `Import error, can't find file: ./runConcent` if we want to run as is. 

Thanks for the great work! I will keep an eye on this project.

**Comment by fantasticsoul** [comment]
> The example given in the README may need an update.
> 
> It gives error `Import error, can't find file: ./runConcent` if we want to run as is.
> 
> Thanks for the great work! I will keep an eye on this project.

I've fixed this error😀
https://stackblitz.com/edit/cc-react-router-concent?file=pages%2FProductList.js
